### ISSUE TITLE
Update to work with require.js version 2.0.0

### ISSUE THREAD

**Issue by eeroan** [JulienCabanes/requirejs-tpl#2]
At least is now req.nameToUrl() has changed to  req.toUrl(). 
And for some reason adding 'tpl!navigation.html' throws error "navigation.js" not found!

**Comment by ZeeAgency** [comment]
Thanks for the feedback !
Actually I didn't test yet with Require.js 2. Sad thing if the API is broken...
I'll fix it ASAP.

**Comment by ZeeAgency** [comment]
This should help :) I've tested really quick with the demo and it seems OK.
Btw, may I know the project, if public, where you're using this plugin ? 
Thanks again !

**Comment by eeroan** [comment]
Working great! That was fast! 

I have bunch of helper functions that are used on templates. 
Could they be somehow available for templates implicitly?
Instead of saying:

myTemplate(_.extend(helperFunctions, {name: 'john'})

I would like to just say:

myTemplate({name: 'john'})

I don't want to put them in global namespace either. Any suggestions for having some configuration hook?

**Comment by ZeeAgency** [comment]
Nice feature request actually, I have the same needs currently and didn't took the time to make it. I'll see what I can do :)

**Comment by eeroan** [comment]
Perhaps having tplHelpers in config could be the right way of passing the default helpers for templates?

require.config({
    tplHelpers: {formattedDate: function(date) {...}}
  })
